name: 'Builds containers and pushes them only if changed'
description: 'Returns a JSON array of containers within a target path'
inputs:
  directory:
    description: 'The parent directory to scan'
    required: false
    default: 'containers'
  repo:
    description: 'The repository'
    required: false
    default: "ghcr.io/${{ github.repository }}"
  arch:
    description: 'CPU Architecture'
    required: true
  os:
    description: 'Operating system'
    required: true
  certificate-identity:
    description: 'identity to verify in the certificate'
    required: true

outputs:
  containers:
    description: 'A JSON array string of container names'
    value: ${{ steps.get-containers.outputs.containers }}
  updated:
    description: 'A JSON array string of container names that were updated'
    value: ${{ steps.build.outputs.updated }}

runs:
  using: "composite"
  steps:
    - name: Get directory list
      id: get-containers
      shell: bash
      run: |
        TARGET_DIR="${{ inputs.directory }}"
        if [ -z "$TARGET_DIR" ]; then
          TARGET_DIR="containers"
        fi

        # Check if directory exists to avoid silent failure
        if [ ! -d "$TARGET_DIR" ]; then
          echo "::error::Directory $TARGET_DIR does not exist."
          exit 1
        fi

        DIRS=$(find "$TARGET_DIR" -maxdepth 1 -mindepth 1 -type d -printf '%P\n')

        for D in $DIRS; do
          DIR_NAME="${D#./}"
          BUILD_FILE="$TARGET_DIR/$DIR_NAME/build.yaml"

          if [[ -f "$BUILD_FILE" ]]; then
            DEPS=$(yq eval '.dependencies // [] | .[]' "$BUILD_FILE")

            if [[ -n "$DEPS" ]]; then
              for DEP in $deps; do
                echo "$DIR_NAME $DEP"
              done
            fi
          fi

          echo "$DIR_NAME $DIR_NAME"
        done | tsort | jq -R . | jq -sc . > /tmp/containers.txt

        echo "containers=$(cat /tmp/containers.txt)"
        echo "containers=$(cat /tmp/containers.txt)" >> $GITHUB_OUTPUT

    - name: Safe Iterate JSON array
      id: build
      shell: bash
      env:
        CONTAINER_JSON: ${{ steps.get-containers.outputs.containers }}
        COSIGN_YES: "true"
      run: |
        is_path_safe() {
          local ROOT_DIR="$1"
          local TEST_PATH="$2"
          local CANONICAL_ROOT=$(readlink -f "$ROOT_DIR")
          local CANONICAL_TEST=$(readlink -f "$TEST_PATH")
          if [[ "$CANONICAL_TEST" == "$CANONICAL_ROOT"* ]]; then
            return 0
          else
            echo "Failed relative path security test $TEST_ROOT, $TEST_PATH, $CANONICAL_TEST == $CANONICAL_ROOT*"
            return 1
          fi
        }
        set -e
        BUILDROOT=$(pwd)
        MAINTAG="latest-${{ inputs.os }}-${{ inputs.arch }}"
        DATETAG=$(date -u +"%Y%m%d-%H%M%S")
        if [ -f timestamp.txt ]; then
          DATETAG=$(cat timestamp.txt)
        fi
        FINALTAG="${{ inputs.os }}-${{ inputs.arch }}-$DATETAG"
        FIRST=1
        OUTPUT=""
        while read -r container; do
          CONTAINER_NAME="${{ inputs.repo }}/$container"
          echo "Buiding container: $container"
          pushd "${{ inputs.directory }}/$container/"
          CONTAINERFILE=$(yq '.containerFile // "Dockerfile"' build.yaml 2>/dev/null || echo "Dockerfile")
          CONTEXT=$(yq '.context // "."' build.yaml 2>/dev/null || echo ".")
          is_path_safe "$BUILDROOT" "$CONTAINERFILE"
          is_path_safe "$BUILDROOT" "$CONTEXT"
          BUILD_ARGS_FLAGS=""
          if [ -f "build.yaml" ]; then
            BUILD_ARGS_FLAGS=$(yq '.buildArgs | select(. != null) |  with_entries(.key + "=" + .value) | .[] | "--build-arg " + .' "build.yaml")
          fi
          echo "Containerfile: $CONTAINERFILE"
          echo "Context: $CONTEXT"
          docker build $BUILD_ARGS_FLAGS -t "$CONTAINER_NAME:$FINALTAG" -f "$CONTAINERFILE" "$CONTEXT"
          syft scan "$CONTAINER_NAME:$FINALTAG" -o spdx-json > sbom.json
          ls -lh sbom.json

          DIFFERENCE=1
          set +e
          cosign verify-attestation \
            --certificate-identity "${{ inputs.certificate-identity }}" \
            --certificate-github-workflow-repository "${{ github.repository }}" \
            --certificate-oidc-issuer "https://token.actions.githubusercontent.com" \
            --type https://spdx.dev/Document \
            "$CONTAINER_NAME:$MAINTAG" > raw_verification.json
          if [ $? -eq 0 ]; then
            REMOTE_SBOM_URI=$(cat raw_verification.json | jq -r '.payload | @base64d | fromjson | .predicate.reference')
            echo "Verified Link Found: $REMOTE_SBOM_URI"
            crane export "$REMOTE_SBOM_URI" - > existing-sbom.json
            ls -l existing-sbom.json
          fi
          if [ -s existing-sbom.json ]; then
            echo Found existing container sbom
            jq -n --arg ref "$CONTAINER_NAME"  '{"max_added": 0, "max_removed": 0, "max_changed": 0, "deny_downgrades": true, "deny_duplicates": false, "ignore": [{"name": $ref, "fields": ["version", "hashes"]}]}' > /tmp/policy.json
            cat /tmp/policy.json
            jq '(.packages[] | select(.name == "ghcr.io/kfox1111/testing-bootc-rpi/test")) |= del(.versionInfo, .checksums)' existing-sbom.json > existing.clean.json
            jq '(.packages[] | select(.name == "ghcr.io/kfox1111/testing-bootc-rpi/test")) |= del(.versionInfo, .checksums)' sbom.json > sbom.clean.json
            sbomlyze existing.clean.json sbom.clean.json --policy /tmp/policy.json --ignore-root
            DIFFERENCE=$?
          fi
          set -e
          if [ $DIFFERENCE -ne 0 ]; then
            echo Difference detected. Pushing image "$CONTAINER_NAME:$FINALTAG"
            docker tag "$CONTAINER_NAME:$FINALTAG" "$CONTAINER_NAME:$MAINTAG"
            docker push "$CONTAINER_NAME:$FINALTAG"
            ls -l sbom.json
            SBOM_DIGEST=$(cosign upload blob -f sbom.json "$CONTAINER_NAME:$FINALTAG.sbom")
            jq -n --arg ref "$SBOM_DIGEST" \
              '{reference: $ref, type: "spdx-json"}' > link.json
            cat link.json
            cosign attest --timeout 600s --type https://spdx.dev/Document \
              --predicate link.json \
              "$CONTAINER_NAME:$FINALTAG"
            docker push "$CONTAINER_NAME:$MAINTAG"
            if [ $FIRST -ne 1 ]; then
              OUTPUT="$OUTPUT,"
            fi
            OUTPUT="$OUTPUT"'"'"$container"'"'
            FIRST=0
          else
            echo No difference detected in "$CONTAINER_NAME:$FINALTAG"
          fi
          popd
        done <<< "$(echo $CONTAINER_JSON | jq -r '.[]')"
        echo "updated=[$OUTPUT]"
        echo "updated=[$OUTPUT]" >> $GITHUB_OUTPUT
