name: 'Builds containers and pushes them only if changed'
description: 'Returns a JSON array of containers within a target path'
inputs:
  directory:
    description: 'The parent directory to scan'
    required: false
    default: 'containers'
  repo:
    description: 'The repository'
    required: true
outputs:
  containers:
    description: 'A JSON array string of container names'
    value: ${{ steps.get-containers.outputs.containers }}

runs:
  using: "composite"
  steps:
    - name: Get directory list
      id: get-containers
      shell: bash
      run: |
        TARGET_DIR="${{ inputs.directory }}"
        
        # Check if directory exists to avoid silent failure
        if [ ! -d "$TARGET_DIR" ]; then
          echo "::error::Directory $TARGET_DIR does not exist."
          exit 1
        fi

        # Find folders, format as JSON array ["dir1", "dir2"]
        DIRS=$(find "$TARGET_DIR" -maxdepth 1 -mindepth 1 -type d -printf '"%f",' | sed 's/,$//')
        
        echo "containers=[$DIRS]" >> $GITHUB_OUTPUT

    - name: Safe Iterate JSON array
      id: build
      shell: bash
      env:
        CONTAINER_JSON: ${{ steps.get-containers.outputs.containers }}
        COSIGN_YES: "true"
      run: |
        set -e
        echo $CONTAINER_JSON | jq -r '.[]' | while read -r container; do
          CONTAINER_NAME="${{ inputs.repo }}/$container"
          echo "Buiding container: $container"
          pushd "${{ inputs.directory }}/$container/"
          docker build -t "$CONTAINER_NAME" .
          syft scan "$CONTAINER_NAME" -o spdx-json > sbom.json
          ls -lh sbom.json

          # Bash style truth
          DIFFERENCE=0
          set +e
          cosign verify-attestation \
            --certificate-identity "https://github.com/kfox1111/testing-repo/.github/workflows/main.yml@refs/heads/main" \
            --certificate-oidc-issuer "https://token.actions.githubusercontent.com" \
            --type https://spdx.dev/Document \
            "$CONTAINER_NAME" | \
            jq -r .payload | \
            base64 -d | jq .predicate > existing-sbom.json
          ls -l existing-sbom.json
          if [ -s existing-sbom.json ]; then
            echo Found existing container sbom
            sbomlyze existing-sbom.json sbom.json
            DIFFERENCE=$?
          fi
          set -e
          if [ $DIFFERENCE -eq 0 ]; then
            echo Difference detected. Pushing image "$CONTAINER_NAME"
            docker push "$CONTAINER_NAME"
            cosign attest --type spdxjson \
              --predicate sbom.json \
              "$CONTAINER_NAME"
          else
            echo No difference detected in "$CONTAINER_NAME"
          fi
          popd
        done